name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2  # Fixed version

        with:
          path: '.'  # Folder with your site content

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # Fixed version
